### ISSUE TITLE
Diagram in `./dag/README.md` is Broken

### ISSUE THREAD

**Issue by dmarzzz** [iykyk-syn/unison#54]
https://github.com/iykyk-syn/unison/tree/main/dag#dag shows which looks like its missing the ending tag : 

> <style class="style-fonts"> @font-face { font-family: "Virgil"; src: url("https://excalidraw.com/Virgil.woff2"); } @font-face { font-family: "Cascadia"; src: url("https://excalidraw.com/Cascadia.woff2"); } @font-face { font-family: "Assistant"; src: url("https://excalidraw.com/Assistant-Regular.woff2"); } </style> Height99Height99Height99Height99Height 100Height101Height100Height100Height100Height101Height101Height101Regular BlockchainDAG chain of BlocksProposer 1 Proposer 1Proposer 2Proposer 3Proposer 2Proposer 3

**Comment by abstraking** [comment]
Thanks for reporting. This is being fixed in https://github.com/iykyk-syn/unison/pull/55 now. Can you confirm it works for you now?
